logging:
  level:
    #    io:
    #      netty: debug
    org:
      springframework.data: trace
    com:
      psawesome:
        basepackage:
          learningreactivefile: debug
    reactor:
      core: trace
      util: trace


spring:

  data:
    mongodb:
      host: localhost
      port: 27017
